config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lixodones
  resources :lixotodos do
    resource :download, only: [:show]
  end
  resources :quartos
  resources :cursos
  resources :residentes
  resources :periodos
  resource :user_sessions, :only => [:create, :new, :destroy]

  root :to => "residentes#index"
  get 'tabela/lixo', to: 'downloads#show', as: 'tabela/lixo'
  get 'lixotodos_tupla/:data', to: 'lixotodos#tupla', as: 'lixotodos_tupla'
  get 'populate_lixotodos', to: 'application#populate_lixotodos', as: 'populate_lixotodos'
  get 'refresh_lixodones', to: 'application#refresh_lixodones', as: 'refresh_lixodones'
  get 'populate_residentes', to: 'application#populate_residentes', as: 'populate_residentes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lixodone.rb
class Lixodone < ApplicationRecord
  has_many :residentes
  validates_uniqueness_of :residente_id
  validates_presence_of :residente_id

  def residente
    @residente = Residente.find(self.residente_id)
  end
end

app/controllers/lixodones_controller.rb
class LixodonesController < ApplicationController
  before_action :set_lixodone, only: [:show, :edit, :update, :destroy]
  before_filter :require_authentication,
                :only => [:new, :edit, :create, :update, :destroy]

  # GET /lixodones
  # GET /lixodones.json
  def index
    @lixodones = Lixodone.all
  end

  # GET /lixodones/1
  # GET /lixodones/1.json
  def show
  end

  # GET /lixodones/new
  def new
    @lixodone = Lixodone.new
  end

  # GET /lixodones/1/edit
  def edit
  end

  def name
    respond_to do |format|
      format.html { "Residentes que já cumpriram a tabela" }
    end
  end

  # POST /lixodones
  # POST /lixodones.json
  def create
    @lixodone = Lixodone.new(lixodone_params)

    respond_to do |format|
      if @lixodone.save
        format.html { redirect_to @lixodone, notice: 'Lixodone was successfully created.' }
        format.json { render :show, status: :created, location: @lixodone }
      else
        format.html { render :new }
        format.json { render json: @lixodone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lixodones/1
  # PATCH/PUT /lixodones/1.json
  def update
    respond_to do |format|
      if @lixodone.update(lixodone_params)
        format.html { redirect_to @lixodone, notice: 'Lixodone was successfully updated.' }
        format.json { render :show, status: :ok, location: @lixodone }
      else
        format.html { render :edit }
        format.json { render json: @lixodone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lixodones/1
  # DELETE /lixodones/1.json
  def destroy
    @lixodone.destroy
    respond_to do |format|
      format.html { redirect_to lixodones_url, notice: 'Lixodone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lixodone
      @lixodone = Lixodone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lixodone_params
      params.require(:lixodone).permit(:residente_id, :data)
    end
end

app/helpers/lixodones_helper.rb
module LixodonesHelper
end

app/views/lixodones/_form.html.erb
<script>
    function checkform() {
        var x = document.getElementById("residenteid").selectedIndex;
        var valor = document.getElementsByTagName("option")[x].value;
        document.getElementById("lixodone_residente_id").setAttribute("value", valor);
    }
</script>
<%= form_for(lixodone, :html=>{:name=>"f",:onsubmit=>"return checkform();"}) do |f| %>
    <div class="form-group" style="border-bottom: double 1px #dddddd;">
      <div class="col-sm-10">
        <h5>Adicionar residente manualmente à tabela</h5>
      </div>
    </div>
    <% if lixodone.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(lixodone.errors.count, "error") %> prohibited this lixotodo from being saved:</h2>

          <ul>
            <% lixodone.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :residente_id %>
      <div class="col-sm-10">
        <% if action_name.to_s.casecmp('edit')==0 %>
            <%= f.text_field :res, :value => @lixodone.residente.nome, :disabled => true %>
            <%= f.hidden_field :residente_id %>
        <% else %>
            <%= select_tag "residente", options_from_collection_for_select(Residente.order("nome"), "id", "nome"), include_blank: true, id: "residenteid", data: { placeholder: "Escolha um residente" } %>
            <%= f.hidden_field :residente_id %>
        <% end %>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :data %>
      <div class="col-sm-10">
        <%= f.date_select :data, :format => :default %>
      </div>
    </div>

    <div class="actions">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/lixodones/edit.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>
<h1>Editing Lixodone</h1>

<%= render 'form', lixodone: @lixodone %>

<%= link_to 'Show', @lixodone %> |
<%= link_to 'Back', lixodones_path %>

app/views/lixodones/index.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>
<% flag = 0 %>
<tbody>
  <% @lixodones.each do |lixodone| %>
      <% if flag%2 == 0 %>
          <div class="panel panel-default panel-lixotodo" style="border-top: none;">
            <div class="panel-heading" style="background: #333; color: #eeeeee">
              <h3 class="panel-title"><i class="fa fa-clock-o fa-tasks"></i> <%= lixodone.data %></h3>
            </div>
            <div class="panel-body">
      <% end %>
      <div class="list-group row">
        <div class="col-lg-9">
          <a href="<%= lixodone_path(lixodone.id) %>" class="list-group-item">
            <i class="fa fa-fw fa-user"></i> <%= lixodone.residente.nome %> &emsp;  &emsp;
            <i class="fa fa-fw fa-calendar"></i> <%= lixodone.data %>
          </a>
        </div>
        <div class="col-md-3 list-group-item" style="border: none;">
          <% if user_signed_in? %>
            <a class="label label-default" href="<%= edit_lixodone_path(lixodone) %>">Editar</a>
            <%= link_to t('.destroy'), lixodone, method: :delete, :class => 'label label-danger', data: { confirm: 'Tem certeza?' } %>
          <% else %>
              <button class="label label-default btn" disabled="disabled">Editar</button>
              <button class="label label-danger btn" disabled="disabled">Excluir registro</button>
          <% end %>
        </div>
      </div>
      <% if flag%2 != 0 %>
          </div>
          </div>
      <% end %>
      <% flag = flag+1 %>
  <% end %>
  <div class="text-right">
    <a href="#">Ver todos <i class="fa fa-arrow-circle-right"></i></a>
  </div>
  </tbody>
</table>

app/views/lixodones/new.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>

<%= render 'form', lixodone: @lixodone %>

<%= link_to 'Back', lixodones_path %>

app/views/lixodones/show.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>

<div class="panel panel-default panel-lixotodo" style="border-top: none;">
  <div class="panel-heading" style="background: #333; color: #eeeeee">
    <h3 class="panel-title"><i class="fa fa-check-square-o"></i> Tarefa cumprida</h3>
  </div>
  <div class="panel-body">
    <div class="list-group row">
      <div class="col-lg-12">
        <a href="/residentes/<%= @lixodone.residente_id %>" class="list-group-item">
          <i class="fa fa-fw fa-user"></i> <b>Residente: </b> &emsp;  &emsp;
          <%= @lixodone.residente.nome %>
        </a>
        <div class="list-group-item">
          <i class="fa fa-fw fa-calendar"></i> <b>Data: </b> &emsp;  &emsp;
          <%= @lixodone.data %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Editar', edit_lixodone_path(@lixodone) %> |
<%= link_to 'Voltar', lixodones_path %>