config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lixodones
  resources :lixotodos do
    resource :download, only: [:show]
  end
  resources :quartos
  resources :cursos
  resources :residentes
  resources :periodos
  resource :user_sessions, :only => [:create, :new, :destroy]

  root :to => "residentes#index"
  get 'tabela/lixo', to: 'downloads#show', as: 'tabela/lixo'
  get 'lixotodos_tupla/:data', to: 'lixotodos#tupla', as: 'lixotodos_tupla'
  get 'populate_lixotodos', to: 'application#populate_lixotodos', as: 'populate_lixotodos'
  get 'refresh_lixodones', to: 'application#refresh_lixodones', as: 'refresh_lixodones'
  get 'populate_residentes', to: 'application#populate_residentes', as: 'populate_residentes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lixotodo.rb
class Lixotodo < ApplicationRecord
  has_many :residentes
  validates_uniqueness_of :residente_id
  validates_presence_of :residente_id

  def residente
    @residente = Residente.find(self.residente_id)
  end

end

app/controllers/lixotodos_controller.rb
class LixotodosController < ApplicationController
  before_action :set_lixotodo, only: [:show, :edit, :update, :destroy]
  before_filter :require_authentication,
                :only => [:new, :edit, :create, :update, :destroy]


  # GET /lixotodos
  # GET /lixotodos.json
  def index
    @lixotodos = Lixotodo.order("data")
  end

  # GET /lixotodos/1
  # GET /lixotodos/1.json
  def show
  end

  # GET /lixotodos/new
  def new
    @lixotodo = Lixotodo.new
  end

  # GET /lixotodos/1/edit
  def edit
  end

  # POST /lixotodos
  # POST /lixotodos.json
  def create
    @lixotodo = Lixotodo.new(lixotodo_params)

    respond_to do |format|
      if @lixotodo.save
        format.html {redirect_to @lixotodo, notice: 'Registro criado com sucesso!'}
        format.json {render :show, status: :created, location: @lixotodo}
      else
        format.html {render :new}
        format.json {render json: @lixotodo.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /lixotodos/1
  # PATCH/PUT /lixotodos/1.json
  def update
    respond_to do |format|
      lixotodo_sub = Lixotodo.find(params[:lixotodo_sub_id])
      lixotodo_sub.destroy
      if @lixotodo.update(lixotodo_params)
        refresh_lixotodo_after_edit(@lixotodo)
        format.html {redirect_to populate_lixotodos_path, notice: 'Tabela de lixo atualizada com sucesso.'}
        format.json {render :show, status: :ok, location: @lixotodo}
      else
        format.html {render :edit}
        format.json {render json: @lixotodo.errors, status: :unprocessable_entity}
      end
    end
  end

  def name
    respond_to do |format|
      format.html {"Tabela de lixo"}
    end
  end

  # DELETE /lixotodos/1
  # DELETE /lixotodos/1.json
  def destroy
    @lixotodo.destroy
    respond_to do |format|
      format.html {redirect_to lixotodos_url, notice: 'Registro excluído com sucesso.'}
      format.json {head :no_content}
    end
  end

  def tupla
    dia = Time.zone.parse(params[:data])
    if dia.on_weekend?
      respond_to do |format|
        format.html { redirect_to edit_lixotodo_path, notice: 'O dia não pode ser em um fim de semana.'}
      end
    else
      @lixotodos = Lixotodo.where("data = ?", params[:data])
      render :partial => "tupla", locals: {lixotodos: @lixotodos}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_lixotodo
    @lixotodo = Lixotodo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lixotodo_params
    params.require(:lixotodo).permit(:residente_id, :data, :lixotodo_sub_id)
  end
end

app/helpers/lixotodos_helper.rb
module LixotodosHelper
end

app/views/lixotodos/_add_lixotodos.html.erb
<% if populate_lixotodos %>
    Suecesso!
<% else %>
    Fail!
<% end %>

app/views/lixotodos/_form.html.erb
<script>

    function checkform() {
        var x = document.getElementById("residenteid").selectedIndex;
        var valor = document.getElementsByTagName("option")[x].value;
        document.getElementById("lixotodo_residente_id").setAttribute("value", valor);

    }

    function change_lixotodo_item() {
        var lixotodo_id;
        var radio1 = document.getElementById("radio1");
        if (radio1.checked) {
            //alert("Checked! " + radio1.value);
            lixotodo_id = radio1.value;
        } else {
            var radio2 = document.getElementById("radio2");
            //alert("Not Checked! " + radio2.value);
            lixotodo_id = radio2.value;
        }
        document.getElementById("lixotodo_sub_id").setAttribute("value", lixotodo_id);

    }


</script>

<%= form_for(lixotodo, :html => {:name => "f", :onsubmit => "return checkform();"}) do |f| %>
    <div class="form-group" style="border-bottom: double 1px #dddddd;">
      <div class="col-sm-10">
        <h5>Selecione a data para a tarefa.</h5>
      </div>
    </div>
    <% if lixotodo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(lixotodo.errors.count, "error") %> impedem de salvar a tarefa:</h2>

          <ul>
            <% lixotodo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :residente_id %>
      <div class="col-sm-10">
        <% if action_name.to_s.casecmp('edit')==0 %>
            <%= f.text_field :res, :value => @lixotodo.residente.nome, :disabled => true %>
            <%= f.hidden_field :residente_id %>
        <% else %>
            <%= select_tag "residente", options_from_collection_for_select(Residente.order("nome"), "id", "nome"), include_blank: true, id: "residenteid", data: {placeholder: "Escolha um residente"} %>
            <%= f.hidden_field :residente_id %>
        <% end %>
      </div>

    </div>

    <div class="form-group">
      <%= f.label :data %>
      <div class="col-sm-10" data-toggle="tooltip" title="Clique para selecionar a nova data para realização da tarefa.">
        <%= f.text_field :data %>

      </div>
    </div>

    <div class="form-group" id="tupla">
    </div>
    <input id="lixotodo_sub_id" name="lixotodo_sub_id" value="" hidden>

    <div class="actions">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :onclick => "change_lixotodo_item()" %>
      </div>
    </div>

<% end %>

app/views/lixotodos/_tupla.html.erb
<div class="col-sm-2">
</div>
<div class="col-sm-10">
  <div class="panel panel-default panel-lixotodo" style="border-top: none;">
    <div class="panel-heading" style="background: #333333; color: #ffffff">
      <h3 style="text-align: center;" class="panel-title"><i class="fa fa-trash-o"></i> Selecione o residente a ser
        substituído</h3>
    </div>
    <div class="panel-body">
      <div class="list-group row">
        <div class="col-lg-10">
          <label class="list-group-item" id="residente1" for="radio1" style="width: 100%; text-align: left;">
            <input class="form-check-input" type="radio" name="radio" id="radio1" value="<%= @lixotodos.first.id %>" checked>
            &emsp; &emsp;
            <i class="fa fa-fw fa-user"></i> <b>Residente: </b>
            <%= @lixotodos.first.residente.nome %>
          </label>
        </div>
      </div>
      <div class="list-group row">
        <div class="col-lg-10">
          <label class="list-group-item" id="residente2" for="radio2" style="width: 100%; text-align: left;">
            <input class="form-check-input" type="radio" name="radio" id="radio2" value="<%= @lixotodos.last.id %>">
            &emsp; &emsp;
            <i class="fa fa-fw fa-user"></i> <b>Residente: </b>
            <%= @lixotodos.last.residente.nome %>
          </label>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lixotodos/_update_lixotodos.html.erb
<%= link_to render(partial: 'layouts/ttip_lixotodo'), lixotodos_path %>
<%= link_to render(partial: 'layouts/ttip_lixodone'), lixodones_path %>
<% if user_signed_in? %>
  <% if controller_name == 'lixotodos' %>
      <%= link_to render(partial: 'layouts/ttip_update_lixotodo'), populate_lixotodos_path %>
      <%= link_to render(partial: 'layouts/ttip_pdf'),
                  tabela_lixo_path(format: "pdf"),
                  target: "_blank",
                  class: "download" %>
  <% else %>
      <%= link_to render(partial: 'layouts/ttip_update_lixodone'), refresh_lixodones_path %>
  <% end %>
<% end %>

app/views/lixotodos/edit.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>
<h3>Antecipar tarefa</h3>

<%= render 'form', lixotodo: @lixotodo %>

<%= link_to 'Show', @lixotodo %> |
<%= link_to 'Back', lixotodos_path %>

app/views/lixotodos/index.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>
<% flag = 0 %>
<table>
  <tbody>
  <% @lixotodos.each do |lixotodo| %>
    <% if flag%2 == 0 %>
      <div class="panel panel-default panel-lixotodo" style="border-top: none;">
        <div class="panel-heading" style="background: #333; color: #eeeeee">
          <h3 class="panel-title" data-toggle="tooltip" title="Data da tarefa."><i class="fa fa-clock-o fa-tasks"></i> <%= lixotodo.data %></h3>
        </div>
        <div class="panel-body">
    <% end %>
          <div class="list-group row">
            <div class="col-lg-9">
              <a data-toggle="tooltip" title="Clique para visualizar detalhes." href="<%= lixotodo_path(lixotodo.id) %>" class="list-group-item">
                <i class="fa fa-fw fa-user"></i> <%= lixotodo.residente.nome %> &emsp;  &emsp;
                <i class="fa fa-fw fa-calendar"></i> <%= lixotodo.data %>
              </a>
            </div>
            <div class="col-md-3 list-group-item" style="border: none;">
              <% if user_signed_in? %>
                <a data-toggle="tooltip" title="Clique para alterar a data em que esse residente realizará sua tarefa." class="label label-default" href="<%= edit_lixotodo_path(lixotodo) %>">ANTECIPAR TAREFA</a>
                <%= link_to t('.destroy'), lixotodo, method: :delete, :class => 'label label-danger', data: { confirm: 'Tem certeza?' } %>
              <% else %>
                  <button class="label label-default btn" disabled="disabled">Editar</button>
                  <button class="label label-danger btn" disabled="disabled">Excluir registro</button>
              <% end %>
            </div>
          </div>
    <% if flag%2 != 0 %>
        </div>
      </div>
    <% end %>
    <% flag = flag+1 %>
  <% end %>
  <div class="text-right">
    <a href="#">Ver todos <i class="fa fa-arrow-circle-right"></i></a>
  </div>
  </tbody>
</table>

app/views/lixotodos/new.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>

<%= render 'form', lixotodo: @lixotodo %>

<%= link_to 'Back', lixotodos_path %>

app/views/lixotodos/pdf.html.erb
<% @lixotodos = Lixotodo.order("data").limit(18).where("data >= ?", Time.now.beginning_of_day) %>
<% flag = 0 %>
<style>

</style>

<div class="pdf-table">
  <header>
    <div class="table-title">
      <b>TABELA DE RETIRADA DO LIXO</b>
    </div>
    <div class="table-description">
      <p>
        Tarefas: descartar o residuo contido nas lixeiras da cozinha e da area de serviço no deposito que fica em frente a Residencia Universitaria.
      </p>
    </div>
  </header>
  <table>
    <tbody>
    <% @lixotodos.each do |lixotodo| %>
        <% if flag%2 == 0 %>
        <p>
        <div class="tupla-panel" >
            <div class="" style="background: #cfd0d1; color: #000000">
              <h3 class="panel-title" style="padding: 3px;"> <strong><%= l(lixotodo.data, :format => :long) %></strong></h3>
            </div>
            <div class="item-group">
        <% end %>
                <div class="item">
                  <b>Nome:</b> <%= lixotodo.residente.nome %> &emsp;  &emsp;
                  <b>Quarto:</b> <%= lixotodo.residente.quarto.numero %> - <%= lixotodo.residente.quarto.piso %>
                </div>
        <% if flag%2 != 0 %>
            </div>
          </div>
            </p>
        <% end %>
        <% flag = flag+1 %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/lixotodos/show.html.erb
<script>
    document.getElementById("menu-tabelas").className = 'active';
</script>

<div class="panel panel-default panel-lixotodo" style="border-top: none;">
  <div class="panel-heading" style="background: #333; color: #eeeeee">
    <h3 class="panel-title"><i class="fa fa-trash-o"></i> Residente registrado</h3>
  </div>
  <div class="panel-body">
    <div class="list-group row">
      <div class="col-lg-12">
        <a href="/residentes/<%= @lixotodo.residente_id %>" class="list-group-item">
          <i class="fa fa-fw fa-user"></i> <b>Residente: </b> &emsp;  &emsp;
          <%= @lixotodo.residente.nome %>
        </a>
        <div class="list-group-item">
          <i class="fa fa-fw fa-calendar"></i> <b>Data: </b> &emsp;  &emsp;
          <%= @lixotodo.data %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Editar', edit_lixotodo_path(@lixotodo) %> |
<%= link_to 'Voltar', lixotodos_path %>