config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lixodones
  resources :lixotodos do
    resource :download, only: [:show]
  end
  resources :quartos
  resources :cursos
  resources :residentes
  resources :periodos
  resource :user_sessions, :only => [:create, :new, :destroy]

  root :to => "residentes#index"
  get 'tabela/lixo', to: 'downloads#show', as: 'tabela/lixo'
  get 'lixotodos_tupla/:data', to: 'lixotodos#tupla', as: 'lixotodos_tupla'
  get 'populate_lixotodos', to: 'application#populate_lixotodos', as: 'populate_lixotodos'
  get 'refresh_lixodones', to: 'application#refresh_lixodones', as: 'refresh_lixodones'
  get 'populate_residentes', to: 'application#populate_residentes', as: 'populate_residentes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/residente.rb
class Residente < ApplicationRecord
  belongs_to :curso
  belongs_to :quarto
  validates_presence_of :nome, :curso_id, :quarto_id, :matricula
  validates_uniqueness_of :matricula

  def quarto
    @quarto = Quarto.find(self.quarto_id)
  end
  def curso
    @curso = Curso.find(self.curso_id)
  end
  # def self.search(term)
  #   if term.nil?
  #     all
  #   else
  #     where('ILIKE :term', term: "%#{term.downcase}%")
  #   end
  #
  # end
end

app/controllers/residentes_controller.rb
class ResidentesController < ApplicationController
  before_action :set_residente, only: [:show, :edit, :update, :destroy]
  before_filter :require_authentication,
                :only => [:new, :edit, :create, :update, :destroy]

  # GET /residentes
  # GET /residentes.json
  def index
    @residentes = Residente.order("nome")
  end

  # GET /residentes/1
  # GET /residentes/1.json
  def show
  end

  def name
    respond_to do |format|
      format.html { "Residentes" }
    end
  end

  # GET /residentes/new
  def new
    @residente = Residente.new
  end

  # GET /residentes/1/edit
  def edit
  end

  # POST /residentes
  # POST /residentes.json
  def create
    @residente = Residente.new(residente_params)

    respond_to do |format|
      if @residente.save
        format.html { redirect_to @residente, notice: 'Residente was successfully created.' }
        format.json { render :show, status: :created, location: @residente }
      else
        format.html { render :new }
        format.json { render json: @residente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residentes/1
  # PATCH/PUT /residentes/1.json
  def update
    respond_to do |format|
      if @residente.update(residente_params)
        format.html { redirect_to @residente, notice: 'Residente was successfully updated.' }
        format.json { render :show, status: :ok, location: @residente }
      else
        format.html { render :edit }
        format.json { render json: @residente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residentes/1
  # DELETE /residentes/1.json
  def destroy
    @residente.destroy
    respond_to do |format|
      format.html { redirect_to residentes_url, notice: 'Residente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residente
      @residente = Residente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residente_params
      params.require(:residente).permit(:matricula, :nome, :curso_id, :quarto_id)
    end
end

app/helpers/residentes_helper.rb
module ResidentesHelper
end

app/views/residentes/_form.html.erb
<%= form_for(residente) do |f| %>
    <div class="form-group" style="border-bottom: double 1px #dddddd;">
      <div class="col-sm-10">
        <h3>Adicionar Residente</h3>
      </div>
    </div>
  <% if residente.errors.any? %>
      <ul>
      <% residente.errors.full_messages.each do |message| %>
            <div class="row">
              <div class="col-lg-12">
                <div class="alert alert-danger alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <i class="fa fa-info-circle"></i> <%= message %>
                </div>
              </div>
            </div>
      <% end %>
      </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :matricula %>
    <div class="col-sm-10">
      <%= f.text_field :matricula %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :nome %>
    <div class="col-sm-10">
      <%= f.text_field :nome %>
    </div>
  </div>

  <div class="form-group">
    <% @cursos = Curso.order("nome") %>
    <%= f.label :curso_id %>
    <div class="col-sm-10">
      <%= f.select :curso_id, @cursos.collect {|curso| [curso.nome, curso.id]} %>
    </div>
  </div>

  <div class="form-group">
    <% @quartos = Quarto.all %>
    <%= f.label :quarto_id %>
    <div class="col-sm-10">
      <%= f.select :quarto_id, @quartos.collect {|quarto| [quarto.numero.to_s + " - " + quarto.piso, quarto.id]} %>
    </div>
  </div>

  <div class="actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/residentes/edit.html.erb
<script>
    document.getElementById("menu-residentes").className = 'active';
</script>
<h1>Editing Residente</h1>

<%= render 'form', residente: @residente %>

<%= link_to 'Show', @residente %> |
<%= link_to 'Back', residentes_path %>

app/views/residentes/index.html.erb
<script>
    document.getElementById("menu-residentes").className = 'active';
</script>

<table>
  <tbody>
  <% @residentes.each do |residente| %>
      <tr>
        <div class="list-group row">
          <div class="col-lg-9">
            <a data-toggle="tooltip" title="Clique para ver todas as informações do residente." href="<%= residente_path(residente.id) %>" class="list-group-item">
              <i class="fa fa-fw fa-user"></i> <%= residente.nome %> &emsp; &emsp;
              <i class="fa fa-fw fa-bed"></i> <%= residente.quarto.numero.to_s + " - " + residente.quarto.piso %>
            </a>
          </div>
          <div class="col-md-3 list-group-item" style="border: none;">
            <% if user_signed_in? %>
                <a data-toggle="tooltip" title="Editar dados do residente." class="label label-default" href="<%= edit_residente_path(residente) %>">Editar</a>
                <%= link_to t('.destroy'), residente, method: :delete, :class => 'label label-danger', data: {confirm: 'Tem certeza?'} %>
            <% else %>
                <button data-toggle="tooltip" title="Você precisa estar logado para realizar qualquer ação." class="label label-default btn" disabled="disabled">Editar</button>
                <button data-toggle="tooltip" title="Você precisa estar logado para realizar qualquer ação." class="label label-danger btn" disabled="disabled">Excluir registro</button>
            <% end %>
          </div>
        </div>
      </tr>

  <% end %>
  <!--<div class="text-right">-->
    <!--<a href="#">Ver todos <i class="fa fa-arrow-circle-right"></i></a>-->
  <!--</div>-->
  </tbody>
</table>

app/views/residentes/new.html.erb
<script>
    document.getElementById("menu-residentes").className = 'active';
</script>
<%= render 'form', residente: @residente %>

<%= link_to 'Back', residentes_path %>

app/views/residentes/show.html.erb
<script>
    document.getElementById("menu-residentes").className = 'active';
</script>

<div class="panel panel-default panel-lixotodo" style="border-top: none;">
  <div class="panel-heading" style="background: #333; color: #eeeeee">
    <h3 class="panel-title"><i class="fa fa-user"></i>  <%= @residente.nome %></h3>
  </div>
  <div class="panel-body">
    <div class="list-group row">
      <div class="col-lg-12">
        <div class="list-group-item">
          <i class="fa fa-fw fa-id-card"></i> <b>Matrícula: </b> &emsp;  &emsp;
          <%= @residente.matricula %>
        </div>
        <div class="list-group-item">
          <i class="fa fa-fw fa-bed"></i> <b>Quarto: </b> &emsp;  &emsp;
          <%= @residente.quarto.numero.to_s + " - " + @residente.quarto.piso %>
        </div>
        <div class="list-group-item">
          <i class="fa fa-fw fa-book"></i> <b>Curso: </b> &emsp;  &emsp;
          <%= @residente.curso.nome %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Editar', edit_residente_path(@residente) %> |
<%= link_to 'Voltar', residentes_path %>