config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lixodones
  resources :lixotodos do
    resource :download, only: [:show]
  end
  resources :quartos
  resources :cursos
  resources :residentes
  resources :periodos
  resource :user_sessions, :only => [:create, :new, :destroy]

  root :to => "residentes#index"
  get 'tabela/lixo', to: 'downloads#show', as: 'tabela/lixo'
  get 'lixotodos_tupla/:data', to: 'lixotodos#tupla', as: 'lixotodos_tupla'
  get 'populate_lixotodos', to: 'application#populate_lixotodos', as: 'populate_lixotodos'
  get 'refresh_lixodones', to: 'application#refresh_lixodones', as: 'refresh_lixodones'
  get 'populate_residentes', to: 'application#populate_residentes', as: 'populate_residentes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_ttip_add.html.erb
<div class="btn btn-info btn-reuper ttip">
  <i class="fa fa-fw fa-plus"></i>
  <div class="btn-text">
    Adicionar
  </div>
  <span class="tooltiptext">Adicionar, manualmente, um novo registro em "<%= controller.name %>".</span>
</div>

app/views/layouts/_ttip_lixodone.html.erb
<div class="btn btn-success btn-reuper ttip">
  <i class="fa fa-fw fa-check-square-o"></i>
  <div class="btn-text">
    Finalizados
  </div>
  <span class="tooltiptext">
    Tabela com residentes que já cumpriram a tarefa de retirada do lixo.
  </span>
</div>

app/views/layouts/_ttip_lixotodo.html.erb
<div class="btn btn-warning btn-reuper ttip">
  <i class="fa fa-fw fa-hourglass-start"></i>
  <div class="btn-text">
    TABELA DE LIXO
  </div>
  <span class="tooltiptext">Tabela de lixo a ser cumprida pelos residentes listados.</span>
</div>

app/views/layouts/_ttip_pdf.html.erb
<div class="btn btn-default btn-reuper ttip">
  <i class="fa fa-fw fa-download"></i>
  <div class="btn-text">
    Gerar PDF
  </div>
  <span class=" tooltiptext">Gerar PDF da tabela de lixo.</span>
</div>

app/views/layouts/_ttip_update_lixodone.html.erb
<div class="btn btn-primary btn-reuper ttip">
  <i class="fa fa-fw fa-refresh"></i>
  <div class="btn-text">
    Atualizar
  </div>
  <span class=" tooltiptext">Atualiza automaticamente a lista dos residentes que já cumpriram a tarefa de retirada do lixo.</span>
</div>

app/views/layouts/_ttip_update_lixotodo.html.erb
<div class="btn btn-primary btn-reuper ttip">
  <i class="fa fa-fw fa-refresh"></i>
  <div class="btn-text">
    Atualizar
  </div>
  <span class=" tooltiptext">Atualiza automaticamente a tabela de lixo para que ela seja preenchida pelos residentes disponíveis.</span>
</div>

app/views/layouts/_user_navbar.html.erb
<script>
    function toggleHelp() {
        $("#opener").toggleClass("helpActive");
        $(".tooltipHelp").toggleClass("invisible");


        var el = $("#opener");
        if (el.text() == el.data("text-swap")) {
            el.text(el.data("text-original"));
        } else {
            el.data("text-original", el.text());
            el.text(el.data("text-swap"));
        }

    }

</script>
<ul class="nav navbar-right top-nav">
  <li>
    <button onclick="toggleHelp()" data-text-swap="Ocultar ajuda" id="opener" type="button" class="dropbtn">
      Mostrar ajuda
    </button>
  </li>
  <li class="dropdn">
    <button class="dropbtn"><i class="fa fa-user-circle-o"></i> <%= current_user.full_name.split(' ').first %>
      <b class="caret"></b></button>
    <ul class="dropdn-content dropdown-menu" style="margin-top: -1px; border-top-right-radius: 0px; border-top-left-radius: 0px; z-index: 0;">
      <li>
        <a href="<%= user_path(current_user) %>"><i class="fa fa-fw fa-user"></i> Meu Perfil</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-fw fa-envelope"></i> Mensagens</a>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to t('layout.signout_html'), user_sessions_path,
                    :method => :delete %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_visitor_navbar.html.erb
<script>
    function toggleHelp() {
        $("#opener").toggleClass("helpActive");
        $(".tooltipHelp").toggleClass("invisible");


        var el = $("#opener");
        if (el.text() == el.data("text-swap")) {
            el.text(el.data("text-original"));
        } else {
            el.data("text-original", el.text());
            el.text(el.data("text-swap"));
        }

    }

</script>

<ul class="nav navbar-right top-nav">
  <li>
    <button onclick="toggleHelp()" data-text-swap="Ocultar ajuda" id="opener" type="button" class="dropbtn">
      Mostrar ajuda
    </button>
  </li>

  <li>
  <a href="<%= new_user_path %>"<i class="fa fa-user-plus" style="color: #51b751"></i> Cadastrar</a>
  </li>
  <li>
  <a href="<%= new_user_sessions_path %>"<i class="fa fa-sign-in" style="color: #74aab7"></i> Login</a>
  </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reuper</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Pacifico|Bungee+Outline|Bungee+Shade|Faster+One'
        rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><p id="reuper">Reuper</p></a>
    </div>

    <!-- Top Menu Items -->
    <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
    <% else %>
        <%= render 'layouts/visitor_navbar' %>
    <% end %>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li id="menu-residentes">
          <a href="<%= residentes_path %>"><i class="fa fa-fw fa-user"></i> Residentes</a>
        </li>
        <li id="menu-quartos">
          <a href="<%= quartos_path %>"><i class="fa fa-fw fa-bed"></i> Quartos</a>
        </li>
        <li id="menu-cursos">
          <a href="<%= cursos_path %>" id="menu-cursos"><i class="fa fa-fw fa-book"></i> Cursos</a>
        </li>
        <li id="menu-tabelas">
          <a href="javascript:;" data-toggle="collapse" data-target="#demo" id="menu-tabelas"><i class="fa fa-fw fa-table"></i>
            Tabelas <i class="fa fa-fw fa-caret-down"></i></a>
          <ul id="demo" class="collapse">
            <li>
              <a href="<%= lixotodos_path %>"><i class="fa fa-fw fa-trash"></i> Lixo</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-fw fa-bitbucket"></i> Cozinha</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-fw fa-snowflake-o"></i> Geladeira</a>
            </li>
            <li>
              <a href="#"><i class="fa fa-fw fa-cutlery"></i> Alimentação</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </nav>

  <div id="page-wrapper">

    <div class="tooltipHelp invisible" id="dialog-message" title="Download complete">
      <div class="panel panel-default panel-lixotodo" style="border-top: none;">
        <div class="panel-heading" style="background: #333; color: #eeeeee">
          <h3 class="panel-title"><i class="fa fa-warning"></i> AJUDA</h3>
        </div>
        <div class="panel-body">
          <div class="list-group row">
            <div class="col-lg-12">
              <p>
                Para exibir ajuda para cada função do sistema, passe o cursor do mouse por cima de um elemento (botão, texto, link, etc.)
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <!-- Page Heading -->
      <div class="row">
        <div class="col-lg-12 page-header">
          <p>
          <h2>
            <%= controller.name %>
            <% if user_signed_in? %>
                <a class="invisible" href="<%= populate_residentes_path %>"> <i class="fa fa-refresh"></i></a>
            <% end %>
          </h2>

          </p>

          <div class="text-center">
            <% if controller_name == 'lixotodos' || controller_name == 'lixodones' %>
                <%= render 'lixotodos/update_lixotodos' %>
            <% end %>
            <% if user_signed_in? %>
                <%= link_to render(partial: 'layouts/ttip_add'), action: :new %>
            <% end %>

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12">


          <div id="content">

            <% if notice.present? %>
                <div class="row">
                  <div class="col-lg-12">
                    <div class="alert alert-info alert-dismissable" id="notice">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <i class="fa fa-info-circle"></i> <%= notice %>
                    </div>
                  </div>
                </div>
            <% end %>
            <% if alert.present? %>
                <div class="row" id="alert">
                  <div class="col-lg-12">
                    <div class="alert alert-warning alert-dismissable">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <i class="fa fa-info-circle"></i> <%= alert %>
                    </div>
                  </div>
                </div>
            <% end %>
            <%= yield %>
          </div>


        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<%= javascript_include_tag "application" %>

<script type="text/javascript">

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });

    prettyPrint();

    //$('select#residenteid').select2();

    $('select#residenteid').select2({
        placeholder: "Selecione um residente",
        allowClear: false
    });

    $(function () {
        $("#lixotodo_data").datepicker();
    });


    function formatExample(residente) {
        var originalOption = $(residente.element);
        return "<span style='display: inline; background-color: " + originalOption.data("favoriteColor").toLowerCase() + "'>&nbsp;&nbsp;</span> " + residente.text;
    }
    $('select#template-example').select2({
        formatResult: formatExample,
        formatSelection: formatExample,
        escapeMarkup: function (m) {
            return m;
        }
    });

    $('#ajax-example').select2({
        ajax: {
            url: "<%= residentes_path(format: 'json') %>",
            dataType: "json",
            results: function (data, page) {
                return {
                    results: $.map(data, function (residente, i) {
                        return {id: residente.id, text: residente.name}
                    })
                }
            }
        }
    });

    $("#lixotodo_data").datepicker({
        showButtonPanel: true,
        changeMonth: true,
        altField: "#lixotodo_data",
        altFormat: "yy-mm-dd"
    });
    document.getElementById("lixotodo_data").onclick = function () {
        showLixotodoTupla()
    };
    function showLixotodoTupla() {
        var x = document.getElementById("lixotodo_data");
//            document.getElementById("tupla").addClass("visible");
//            document.getElementById("tupla").removeClass("invisible");
    }
    $("#lixotodo_data").change(function () {
        $("#tupla").addClass("visible").removeClass("invisible");
        var data = document.getElementById("lixotodo_data");
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("tupla").innerHTML =
                    this.responseText;
            }
        };
        xhttp.open("GET", "/lixotodos_tupla/" + data.value, true);
        xhttp.send();
    });


</script>
</body>

</html>

app/views/layouts/lixotodos_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <style>


    .pdf-table{
      padding: 0px;
    }
    .tupla-title{
      margin-top: -18px;
      margin-bottom: -18px;
    }
    .tupla-panel{
      border: 1px solid #2f2f2f;
    }
    .item{
      border-top: 1px solid #2f2f2f;
      padding: 3px;
    }
    .table-title{
      text-align: center;
      font-size: large;
      border: 1px solid #2E2F30;
      padding: 2px;
    }

  </style>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>